version: '3.8'
services:
  auth-service:
    image: registry.ums.local:5000/auth-service:${IMAGE_TAG}
    container_name: auth-service
    restart: always
    ports:
      - "8090:8090"
    extra_hosts:
      - "eureka-server:10.0.0.136"
      - "config-server:10.0.0.141"
      - "kafka:10.0.0.137"
      - "redis:10.0.0.138"
    environment:
      host_ip: "${HOST_IP}"
      SPRING_PROFILES_ACTIVE: dev
      KAFKA_PORT: "9092"
    volumes:
      - /data/auth-service/logs/auth-service:/app/logs
      - /data/auth-service/db:/app/db